// <auto-generated />
using System;
using Fokus.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fokus.Persistence.Migrations
{
    [DbContext(typeof(FokusDbContext))]
    [Migration("20260510104427_AddSprintGoal")]
    partial class AddSprintGoal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0-preview.4.25258.110");

            modelBuilder.Entity("Fokus.Domain.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BoardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BugRatioAlertThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BugRatioConsecutiveSprintCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyDomain")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CycleTimeEndStage")
                        .HasColumnType("TEXT");

                    b.Property<string>("CycleTimeStartStage")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultSpPerBug")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DoneStatuses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExcludedFromScopeStatuses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanningWindowDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncBackSprintCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkflowStages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Fokus.Domain.Auth.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Manager");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_AppUsers_Email");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasDatabaseName("IX_AppUsers_GoogleId");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Fokus.Domain.Auth.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InvitedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Manager");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Invitations_Email");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_Invitations_Token");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("Fokus.Domain.Developer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultCapacityPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(100);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Developer");

                    b.Property<string>("SubTeam")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("Fokus.Domain.DeveloperSprintCapacity", b =>
                {
                    b.Property<string>("DeveloperAccountId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SprintId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacityPercent")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeveloperAccountId", "SprintId");

                    b.HasIndex("SprintId")
                        .HasDatabaseName("IX_DeveloperSprintCapacity_SprintId");

                    b.ToTable("DeveloperSprintCapacities");
                });

            modelBuilder.Entity("Fokus.Domain.Sprint", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoardName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Goal")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedById")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sprints");
                });

            modelBuilder.Entity("Fokus.Domain.SprintMembership", b =>
                {
                    b.Property<int>("SprintId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TicketId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalStatus")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("StoryPoints")
                        .HasColumnType("decimal(8,2)");

                    b.Property<bool>("WasCommitted")
                        .HasColumnType("INTEGER");

                    b.HasKey("SprintId", "TicketId");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("IX_SprintMembership_TicketId");

                    b.ToTable("SprintMemberships");
                });

            modelBuilder.Entity("Fokus.Domain.StatusTransition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TicketId", "Timestamp")
                        .HasDatabaseName("IX_StatusTransition_TicketId_Timestamp");

                    b.ToTable("StatusTransitions");
                });

            modelBuilder.Entity("Fokus.Domain.Ticket", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssigneeId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EpicKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EpicName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedById")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("StoryPoints")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("IX_Ticket_AssigneeId");

                    b.HasIndex("EpicKey")
                        .HasDatabaseName("IX_Ticket_EpicKey");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Fokus.Domain.AppSettings", b =>
                {
                    b.OwnsOne("Fokus.Domain.HealthThresholdConfig", "HealthThresholds", b1 =>
                        {
                            b1.Property<int>("AppSettingsId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("CarryOverAmber")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("CarryOverGreen")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("CompletionAmber")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("CompletionGreen")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("DisruptionAmber")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("DisruptionGreen")
                                .HasColumnType("TEXT");

                            b1.HasKey("AppSettingsId");

                            b1.ToTable("AppSettings");

                            b1.ToJson("HealthThresholds");

                            b1.WithOwner()
                                .HasForeignKey("AppSettingsId");
                        });

                    b.OwnsOne("Fokus.Domain.HealthWeightConfig", "HealthWeights", b1 =>
                        {
                            b1.Property<int>("AppSettingsId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("CarryOver")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Completion")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Disruption")
                                .HasColumnType("INTEGER");

                            b1.HasKey("AppSettingsId");

                            b1.ToTable("AppSettings");

                            b1.ToJson("HealthWeights");

                            b1.WithOwner()
                                .HasForeignKey("AppSettingsId");
                        });

                    b.Navigation("HealthThresholds")
                        .IsRequired();

                    b.Navigation("HealthWeights")
                        .IsRequired();
                });

            modelBuilder.Entity("Fokus.Domain.Auth.Invitation", b =>
                {
                    b.HasOne("Fokus.Domain.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fokus.Domain.DeveloperSprintCapacity", b =>
                {
                    b.HasOne("Fokus.Domain.Developer", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fokus.Domain.Sprint", "Sprint")
                        .WithMany()
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("Fokus.Domain.SprintMembership", b =>
                {
                    b.HasOne("Fokus.Domain.Sprint", "Sprint")
                        .WithMany("Memberships")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fokus.Domain.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sprint");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Fokus.Domain.StatusTransition", b =>
                {
                    b.HasOne("Fokus.Domain.Ticket", "Ticket")
                        .WithMany("StatusTransitions")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Fokus.Domain.Ticket", b =>
                {
                    b.HasOne("Fokus.Domain.Developer", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Assignee");
                });

            modelBuilder.Entity("Fokus.Domain.Sprint", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Fokus.Domain.Ticket", b =>
                {
                    b.Navigation("StatusTransitions");
                });
#pragma warning restore 612, 618
        }
    }
}
