// <auto-generated />
using System;
using Fokus.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fokus.Persistence.Migrations
{
    [DbContext(typeof(FokusDbContext))]
    partial class FokusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0-preview.4.25258.110");

            modelBuilder.Entity("Fokus.Domain.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BoardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DoneStatuses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowStages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Fokus.Domain.Entities.Developer", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubTeam")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("Fokus.Domain.Entities.Sprint", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoardName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sprints");
                });

            modelBuilder.Entity("Fokus.Domain.Entities.SprintMembership", b =>
                {
                    b.Property<int>("SprintId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TicketKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalStatus")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("StoryPoints")
                        .HasColumnType("decimal(8,2)");

                    b.Property<bool>("WasCommitted")
                        .HasColumnType("INTEGER");

                    b.HasKey("SprintId", "TicketKey");

                    b.HasIndex("TicketKey")
                        .HasDatabaseName("IX_SprintMembership_TicketKey");

                    b.ToTable("SprintMemberships");
                });

            modelBuilder.Entity("Fokus.Domain.Entities.StatusTransition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TicketKey", "Timestamp")
                        .HasDatabaseName("IX_StatusTransition_TicketKey_Timestamp");

                    b.ToTable("StatusTransitions");
                });

            modelBuilder.Entity("Fokus.Domain.Entities.Ticket", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssigneeId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EpicKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EpicName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("StoryPoints")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("IX_Ticket_AssigneeId");

                    b.HasIndex("EpicKey")
                        .HasDatabaseName("IX_Ticket_EpicKey");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Fokus.Domain.Entities.AppSettings", b =>
                {
                    b.OwnsOne("Fokus.Domain.ValueObjects.HealthThresholdConfig", "HealthThresholds", b1 =>
                        {
                            b1.Property<int>("AppSettingsId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("CarryOverAmber")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("CarryOverGreen")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("CompletionAmber")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("CompletionGreen")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("DisruptionAmber")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("DisruptionGreen")
                                .HasColumnType("TEXT");

                            b1.HasKey("AppSettingsId");

                            b1.ToTable("AppSettings");

                            b1.ToJson("HealthThresholds");

                            b1.WithOwner()
                                .HasForeignKey("AppSettingsId");
                        });

                    b.OwnsOne("Fokus.Domain.ValueObjects.HealthWeightConfig", "HealthWeights", b1 =>
                        {
                            b1.Property<int>("AppSettingsId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("CarryOver")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Completion")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Disruption")
                                .HasColumnType("INTEGER");

                            b1.HasKey("AppSettingsId");

                            b1.ToTable("AppSettings");

                            b1.ToJson("HealthWeights");

                            b1.WithOwner()
                                .HasForeignKey("AppSettingsId");
                        });

                    b.Navigation("HealthThresholds")
                        .IsRequired();

                    b.Navigation("HealthWeights")
                        .IsRequired();
                });

            modelBuilder.Entity("Fokus.Domain.Entities.SprintMembership", b =>
                {
                    b.HasOne("Fokus.Domain.Entities.Sprint", "Sprint")
                        .WithMany("Memberships")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fokus.Domain.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sprint");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Fokus.Domain.Entities.StatusTransition", b =>
                {
                    b.HasOne("Fokus.Domain.Entities.Ticket", "Ticket")
                        .WithMany("StatusTransitions")
                        .HasForeignKey("TicketKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Fokus.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Fokus.Domain.Entities.Developer", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Assignee");
                });

            modelBuilder.Entity("Fokus.Domain.Entities.Sprint", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Fokus.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("StatusTransitions");
                });
#pragma warning restore 612, 618
        }
    }
}
